<div align="center"> <h1> <font color="Orange"> Numpy - II </font> </h1> </div>

In [1]:
import numpy as np

### Matrix Operations

In [3]:
# create a matrix of 4, 4
a1 = np.arange(1, 17).reshape((4, 4))
print(f'Matrix : \n{a1}')

# diagonal matrix
diagonal_matrix = np.diag([1, 2, 3, 4, 5])
print("\nDiagonal Matrix : \n", diagonal_matrix)
print("\nDiagonal elements are :", np.diag(diagonal_matrix))

# identity matrix using np.identity() : only square identity matrix
print("\nIdentity matrix : \n", np.identity(5, dtype=int))

# eye() : non square identity matrix
print("\nIdentity matrix : \n", np.eye(3, 4, dtype=int))

# lower triangular matrix
l_t= np.tril(a1)
print("\nLower triangular matrix : \n", l_t)

# upper triangular matrix
u_t = np.triu(a1)
print("\nUpper triangular matrix : \n", u_t)

Matrix : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Diagonal Matrix : 
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]

Diagonal elements are : [1 2 3 4 5]

Identity matrix : 
 [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]

Identity matrix : 
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]

Lower triangular matrix : 
 [[ 1  0  0  0]
 [ 5  6  0  0]
 [ 9 10 11  0]
 [13 14 15 16]]

Upper triangular matrix : 
 [[ 1  2  3  4]
 [ 0  6  7  8]
 [ 0  0 11 12]
 [ 0  0  0 16]]


In [12]:
# Multiplication
a2 = np.array((1, 2, 3, 4, 5))
a3 = np.array((8, 7, 6, 5, 4))

# multiplication (for 1D with 1D np.dot() is preferred)
a4 = np.dot(a2, a3)
print(f'\nDot product of two 1D arrays : {a4}')

# 1D with a scalar (* is preferred)
print(f'\nTwice of a3 : {a3 * 2}')

# 2D with 2D (np.matmul() or @ is preferred)
a5 = np.arange(1, 13).reshape((3, 4))
a6 = np.arange(12, 24).reshape((4, 3))
a7 = a5 @ a6
a8 = np.matmul(a5, a6)
print(f'\nMultiplication : \n{a7} \n== {a8}')


Dot product of two 1D arrays : 80

Twice of a3 : [16 14 12 10  8]

Multiplication : 
[[180 190 200]
 [444 470 496]
 [708 750 792]] 
== [[180 190 200]
 [444 470 496]
 [708 750 792]]


In [8]:
a9 = np.arange(1, 13).reshape((3, 4))
a10 = np.arange(15, 27).reshape((3, 4))

# addition
print(f'Sum of {a9} \n\nand {a10}\n\n={a9+a10}')

# subtraction
print(f'\nDifference  of {a9} \n\nand {a10}\n\n={a9-a10}')

# division
print(f'\nDivision of {a9} \n\nand {a10}\n\n={a9/a10}')

Sum of [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

and [[15 16 17 18]
 [19 20 21 22]
 [23 24 25 26]]

=[[16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]]

Difference  of [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

and [[15 16 17 18]
 [19 20 21 22]
 [23 24 25 26]]

=[[-14 -14 -14 -14]
 [-14 -14 -14 -14]
 [-14 -14 -14 -14]]

Division of [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

and [[15 16 17 18]
 [19 20 21 22]
 [23 24 25 26]]

=[[0.06666667 0.125      0.17647059 0.22222222]
 [0.26315789 0.3        0.33333333 0.36363636]
 [0.39130435 0.41666667 0.44       0.46153846]]


### Universal Functions

In [21]:
a11 = np.array((1, 0, 0.3, 0.45, 0.2, 0.5, 0.9, 1), dtype=float)

# sin-cos-tan
print("Sin values : ", np.sin(a11))
print("\nCos values : ", np.cos(a11))
print("\nTan values : ", np.tan(a11))

a12 = np.arange(1, 9).reshape((4, 2))

cummulative_product_array = np.cumprod(a12).reshape((4, 2))
print("Cummulative product array : ", cummulative_product_array)

a13 = np.linspace(1000, 10000, 10).reshape((5, 2))

print("Original array : \n", a13)
log_array = np.log(a13)
print("Log values : ", log_array)

a14 = np.array((12, 26, 48, 68))

print("Lcm of input : ", np.lcm.reduce(a14))
print('Sum using add() and reduce : ', np.add.reduce(a14))

Sin values :  [0.84147098 0.         0.29552021 0.43496553 0.19866933 0.47942554
 0.78332691 0.84147098]

Cos values :  [0.54030231 1.         0.95533649 0.9004471  0.98006658 0.87758256
 0.62160997 0.54030231]

Tan values :  [1.55740772 0.         0.30933625 0.48305507 0.20271004 0.54630249
 1.26015822 1.55740772]
Cummulative product array :  [[    1     2]
 [    6    24]
 [  120   720]
 [ 5040 40320]]
Original array : 
 [[ 1000.  2000.]
 [ 3000.  4000.]
 [ 5000.  6000.]
 [ 7000.  8000.]
 [ 9000. 10000.]]
Log values :  [[6.90775528 7.60090246]
 [8.00636757 8.29404964]
 [8.51719319 8.69951475]
 [8.85366543 8.98719682]
 [9.10497986 9.21034037]]
Lcm of input :  10608
Sum using add() and reduce :  154


### Aggregate or reduction functions

In [52]:
a15 = np.arange(1, 17).reshape((4, 4))
print("Matrix is : \n", a15)

# sum
print("\nTotal sum : ", np.sum(a15))
print("Row wise sum : ", np.sum(a15, axis=1))
print("Column wise sum : ", np.sum(a15, axis=0))

# min, max
print("\nMin value : ", np.min(a15))
print("Max value : ", np.max(a15))
print("Max value row wise : ", np.max(a15, axis=1))

# mean
print("\nMean : ", np.mean(a15))
print("Mean (row wise) : ", np.mean(a15, axis=1))

# any()
print("\nAny True values in array : ", np.any(a15))
print("Any True values in array (row wise) : ", np.any(a15, axis=1))

zero_array = np.zeros((2, 3))
print("Truth value of zero array (any()) : ", np.any(zero_array))

#Using conditionals with any()
a16 = np.arange(17, 33).reshape((4, 4))
print("\nComparing two arrays element wise : ", np.any(a15 > a16))
print("Comparing two arrays element wise (double) : ", np.any(2*a15 == a16))


# all()
print("\nAll are True values in array : ", np.all(a15))
print("All are True values in array (row wise) : ", np.all(a15, axis=1))
print("Truth value of zero array (all()) : ", np.all(zero_array))

print("We cal also call all() like this : ", a15.all())

# all() with conditional chaining
answer_bool = np.all((a15 < a16) & (a16 >= a15*2))
print("All values of one array is greater than the other and are at-least double : ", answer_bool)

# nonzero()
print("\nNon zero indices of the array : ", zero_array.nonzero())
print("Non zero indices of the array : ", np.nonzero(a15))
print("Another example : " ,np.array((1, 0, 3, 4, 0)).nonzero())

print("Non zero indices of the array using flatnonzero() : ", np.flatnonzero(a15))

# count_nonzero()
print("\nNon zero count : ", np.count_nonzero(a15))

Matrix is : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Total sum :  136
Row wise sum :  [10 26 42 58]
Column wise sum :  [28 32 36 40]

Min value :  1
Max value :  16
Max value row wise :  [ 4  8 12 16]

Mean :  8.5
Mean (row wise) :  [ 2.5  6.5 10.5 14.5]

Any True values in array :  True
Any True values in array (row wise) :  [ True  True  True  True]
Truth value of zero array (any()) :  False

Comparing two arrays element wise :  False
Comparing two arrays element wise (double) :  True

All are True values in array :  True
All are True values in array (row wise) :  [ True  True  True  True]
Truth value of zero array (all()) :  False
We cal also call all() like this :  True
All values of one array is greater than the other and are at-least double :  True

Non zero indices of the array :  (array([], dtype=int64), array([], dtype=int64))
Non zero indices of the array :  (array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3], dtype=int64), array([0, 1, 2, 3, 0, 1, 

### Sorting

In [2]:
rng = np.random.default_rng(seed=3245)
a17 = rng.integers(1, 100, size=(5, 5))

# sorting
sorted_copy = np.sort(a17)
print("1. Original Matrix : \n", a17, "\n\nSorted matrix (Row wise) : \n", sorted_copy)

flat_sorted_copy = np.sort(a17, axis=None)
print("\n2. Original Matrix : \n", a17, "\n\nSorted array (flattened) : \n", flat_sorted_copy)

col_sorted_copy = np.sort(a17, axis=0)
print("\n3. Original Matrix : \n", a17, "\n\nSorted matrix (col wise) : \n", col_sorted_copy)

# Sorting structured array
dtype = [('name', 'S15'), ('age', int), ('height', float), ('weight', float)]
values = [('one', 40, 170, 80), ('two', 29, 180, 80), ('three', 60, 160, 70), ('four', 50, 165, 69)]
a18 = np.array(values, dtype=dtype)

print("\nStructured array is : ", a18)
struct_arr_sorted_weight_cp = np.sort(a18, order='weight')
struct_arr_sorted_w_h_cp = np.sort(a18, order=['weight', 'age'])

print('\nSorted array by weight : \n', struct_arr_sorted_weight_cp)
print('\nSorted array by weight (if equal then age) : \n', struct_arr_sorted_w_h_cp)

# argsort()
arg_cp = np.argsort(a17)
print(arg_cp)

1. Original Matrix : 
 [[21 62 16 71 20]
 [98 27 35 51 53]
 [36 20 32 54 82]
 [98 20 54 58 97]
 [36 14 10 19  8]] 

Sorted matrix (Row wise) : 
 [[16 20 21 62 71]
 [27 35 51 53 98]
 [20 32 36 54 82]
 [20 54 58 97 98]
 [ 8 10 14 19 36]]

2. Original Matrix : 
 [[21 62 16 71 20]
 [98 27 35 51 53]
 [36 20 32 54 82]
 [98 20 54 58 97]
 [36 14 10 19  8]] 

Sorted array (flattened) : 
 [ 8 10 14 16 19 20 20 20 21 27 32 35 36 36 51 53 54 54 58 62 71 82 97 98
 98]

3. Original Matrix : 
 [[21 62 16 71 20]
 [98 27 35 51 53]
 [36 20 32 54 82]
 [98 20 54 58 97]
 [36 14 10 19  8]] 

Sorted matrix (col wise) : 
 [[21 14 10 19  8]
 [36 20 16 51 20]
 [36 20 32 54 53]
 [98 27 35 58 82]
 [98 62 54 71 97]]

Structured array is :  [(b'one', 40, 170., 80.) (b'two', 29, 180., 80.) (b'three', 60, 160., 70.)
 (b'four', 50, 165., 69.)]

Sorted array by weight : 
 [(b'four', 50, 165., 69.) (b'three', 60, 160., 70.)
 (b'one', 40, 170., 80.) (b'two', 29, 180., 80.)]

Sorted array by weight (if equal then age) : 


In [36]:
# partition
a19 = np.array((7, 9, 7, 1, 8, 2, 4, 5, 6, 7, 3, 4, 1))
print("Original array is : ", a19)

k = 6
partition_array = np.partition(a19, k)
print(f'Partitioned arrays : {partition_array[:k]}, {partition_array[k]}, {partition_array[k:]}')

k_th_largest_number = np.partition(a19, -k)
print(f'K-th largest number in {a19} is {k_th_largest_number[-k]}')

# argpartition()
indices_partition = np.argpartition(a19, k)
print(f'Indices of partition : {indices_partition[:k]}, {indices_partition[k]}, {indices_partition[k:]}')

Original array is :  [7 9 7 1 8 2 4 5 6 7 3 4 1]
Partitioned arrays : [2 1 4 1 3 4], 5, [5 6 7 7 7 8 9]
K-th largest number in [7 9 7 1 8 2 4 5 6 7 3 4 1] is 6
Indices of partition : [ 5 12 11  3 10  6], 7, [7 8 2 9 0 4 1]
